<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
	<info organisation="org.apache.helix"
		module="helix-agent"
		revision="0.7.2-SNAPSHOT"
		status="integration"
		publication="20141105120156"
	>
		<description homepage="" />
		<m:dependency.management__junit__junit__version>4.11</m:dependency.management__junit__junit__version>
		<m:dependency.management__log4j__log4j__version>1.2.15</m:dependency.management__log4j__log4j__version>
		<m:properties__organization.logo>http://www.apache.org/images/asf_logo_wide.gif</m:properties__organization.logo>
		<m:properties__osgi.export>org.apache.helix.agent*;version=&quot;${project.version};-noimport:=true</m:properties__osgi.export>
		<m:properties__svnImpl>svn</m:properties__svnImpl>
		<m:properties__currentRelease>0.7.1</m:properties__currentRelease>
		<m:properties__osgi.import>
      org.apache.helix*,
      org.apache.commons.cli;version=&quot;[1.2,2)&quot;,
      org.apache.log4j,
      *
    </m:properties__osgi.import>
		<m:properties__helix.release.arguments>-Papache-release</m:properties__helix.release.arguments>
		<m:maven.plugins>org.apache.maven.plugins__maven-remote-resources-plugin__null|org.apache.maven.plugins__maven-remote-resources-plugin__null|org.codehaus.mojo__license-maven-plugin__1.3|org.apache.felix__maven-bundle-plugin__2.3.7|org.apache.maven.plugins__maven-source-plugin__null|org.apache.maven.plugins__maven-surefire-plugin__null|org.apache.maven.plugins__maven-remote-resources-plugin__null|org.apache.maven.plugins__maven-remote-resources-plugin__null|org.codehaus.mojo__license-maven-plugin__1.3|org.apache.felix__maven-bundle-plugin__2.3.7|org.apache.maven.plugins__maven-source-plugin__null|org.apache.maven.plugins__maven-surefire-plugin__null|org.codehaus.mojo__appassembler-maven-plugin__null|org.apache.maven.plugins__maven-assembly-plugin__null</m:maven.plugins>
		<m:dependency.management__junit__junit__scope>test</m:dependency.management__junit__junit__scope>
		<m:properties__svnkit.version>1.7.5-v1</m:properties__svnkit.version>
		<m:properties__distMgmtSnapshotsUrl>https://repository.apache.org/content/repositories/snapshots</m:properties__distMgmtSnapshotsUrl>
		<m:properties__SKIP_INTEGRATION_TESTS>true</m:properties__SKIP_INTEGRATION_TESTS>
		<m:properties__gpg.useagent>true</m:properties__gpg.useagent>
		<m:dependency.management__org.apache.helix__helix-core__version>0.7.2-SNAPSHOT</m:dependency.management__org.apache.helix__helix-core__version>
		<m:dependency.management__org.apache.helix__helix-provisioning__version>0.7.2-SNAPSHOT</m:dependency.management__org.apache.helix__helix-provisioning__version>
		<m:properties__project.build.sourceEncoding>UTF-8</m:properties__project.build.sourceEncoding>
		<m:dependency.management__org.testng__testng__version>6.0.1</m:dependency.management__org.testng__testng__version>
		<m:properties__helix.release.preparationGoals>clean install</m:properties__helix.release.preparationGoals>
		<m:properties__distMgmtSnapshotsName>Apache Development Snapshot Repository</m:properties__distMgmtSnapshotsName>
		<m:dependency.management__org.restlet.jse__org.restlet__version>2.2.1</m:dependency.management__org.restlet.jse__org.restlet__version>
		<m:properties__maven-scm-provider-svnjava.version>2.0.5</m:properties__maven-scm-provider-svnjava.version>
		<m:properties__sourceReleaseAssemblyDescriptor>source-release</m:properties__sourceReleaseAssemblyDescriptor>
		<m:properties__helix.release.performGoals>deploy</m:properties__helix.release.performGoals>
		<m:dependency.management__org.mockito__mockito-all__version>1.9.5</m:dependency.management__org.mockito__mockito-all__version>
		<m:properties__sonar.host.url>https://analysis.apache.org/</m:properties__sonar.host.url>
	</info>
	<configurations>
		<conf name="default" visibility="public" description="runtime dependencies and master artifact can be used with this conf" extends="runtime,master"/>
		<conf name="master" visibility="public" description="contains only the artifact published by this module itself, with no transitive dependencies"/>
		<conf name="compile" visibility="public" description="this is the default scope, used if none is specified. Compile dependencies are available in all classpaths."/>
		<conf name="provided" visibility="public" description="this is much like compile, but indicates you expect the JDK or a container to provide it. It is only available on the compilation classpath, and is not transitive."/>
		<conf name="runtime" visibility="public" description="this scope indicates that the dependency is not required for compilation, but is for execution. It is in the runtime and test classpaths, but not the compile classpath." extends="compile"/>
		<conf name="test" visibility="private" description="this scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases." extends="runtime"/>
		<conf name="system" visibility="public" description="this scope is similar to provided except that you have to provide the JAR which contains it explicitly. The artifact is always available and is not looked up in a repository."/>
		<conf name="sources" visibility="public" description="this configuration contains the source artifact of this module, if any."/>
		<conf name="javadoc" visibility="public" description="this configuration contains the javadoc artifact of this module, if any."/>
		<conf name="optional" visibility="public" description="contains all optional dependencies"/>
	</configurations>
	<publications>
		<artifact name="helix-agent" type="bundle" ext="jar" conf="master"/>
		<artifact name="helix-agent" type="source" ext="jar" conf="sources" m:classifier="sources"/>
	</publications>
	<dependencies>
		<dependency org="org.apache.helix" name="helix-core" rev="0.7.2-SNAPSHOT" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)"/>
		<dependency org="org.restlet.jse" name="org.restlet" rev="2.2.1" force="true" conf="compile->compile(*),master(*);runtime->runtime(*)"/>
		<dependency org="org.testng" name="testng" rev="6.0.1" force="true" conf="test->runtime(*),master(*)">
			<exclude org="junit" module="junit" name="*" type="*" ext="*" conf="" matcher="exact"/>
		</dependency>
		<dependency org="org.apache.helix" name="helix-core" rev="0.7.2-SNAPSHOT" force="true" conf="test->runtime(*),master(*)">
			<artifact name="helix-core" type="test-jar" ext="jar" conf="" m:classifier="tests"/>
		</dependency>
		<override org="log4j" module="log4j" matcher="exact" rev="1.2.15"/>
		<override org="org.mockito" module="mockito-all" matcher="exact" rev="1.9.5"/>
		<override org="org.apache.helix" module="helix-core" matcher="exact" rev="0.7.2-SNAPSHOT"/>
		<override org="org.restlet.jse" module="org.restlet" matcher="exact" rev="2.2.1"/>
		<override org="junit" module="junit" matcher="exact" rev="4.11"/>
		<override org="org.testng" module="testng" matcher="exact" rev="6.0.1"/>
		<override org="org.apache.helix" module="helix-provisioning" matcher="exact" rev="0.7.2-SNAPSHOT"/>
	</dependencies>
</ivy-module>
