name: helix-front
on:
  pull_request:
    branches: [ master ]
    paths:
      - 'helix-front/**'

jobs:
  test:
    name: Test helix-front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: helix-front/package.json
      - name: helix-front format:check
        run: cd helix-front && npm run format:check
        working-directory: helix-front
