# Verify if the PR meets all the requirements for merging on PR review event.

name: PR Pre-merge Check

on:
  pull_request:
    types: [edited]
  pull_request_review:
    types: [submitted]

jobs:
  validate_PR:

    runs-on: ubuntu-latest

    steps:
      - name: Verify All Tasks are Finished
        uses: venkatsarvesh/pr-tasks-completed-action@v1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Verify the PR has been approved
        uses: abinoda/label-when-approved-action@1.0.5
        env:
          APPROVALS: "1"
          ADD_LABEL: "CheckedAndApproved"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
